config {
  type: "view",
  schema: "datastudio",
  tags: ["GDS"]
}
WITH
  maxdate AS (
  SELECT
    MAX(SETTLEMENTDATE) as mx
  FROM
   ${ref("today_Table")})

SELECT
  SETTLEMENTDATE,
  StationName,
  technology,
  FuelSourceDescriptor,
  Region,
  min(latitude) as latitude,
  min(longitude) as longitude,
  sum(SCADAVALUE) AS MW
FROM
  ${ref("today_Table")}
where
   SETTLEMENTDATE = (SELECT mx FROM maxdate LIMIT 1)
  and SCADAVALUE <> 0
group by
  1,
  2,
  3,
  4,
  5
